site_name: Trainite
site_description: Documentation for Trainite
site_url: https://pytorch-ignite.github.io/trainite/
repo_url: https://github.com/pytorch-ignite/trainite

theme:
  name: material
  logo: assets/logo.png
  favicon: assets/logo.png
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css

nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - CLI: cli.md
  - Training: training.md
