[project]
name = "trainite-prototype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "torch",
    "pytorch-ignite",
    "pydantic>=2",
    "PyYAML",
    "tensorboard",
]
[project.scripts]
trainite = "trainite.cli:main"

[tool.uv]
package = true
