[project]
name = "trainite-prototype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2",
    "PyYAML",
    "omegaconf>=2.3.0",
    "tomlkit>=0.15.0",
    "packaging>=26.2",
]


[project.scripts]
trainite = "trainite.cli:main"

[tool.uv]
package = true

[dependency-groups]
generated = [
    "pydantic>=2",
    "PyYAML",
    "omegaconf>=2.3.0",
]
dev = [
    "torch",
    "pytorch-ignite",
    "tensorboard",
]
