import re
from pathlib import Path
from typing import Any, Iterable, Literal, Sequence

import questionary
import tomlkit
import tyro
from packaging.requirements import Requirement
from pydantic import BaseModel, field_validator

from trainite import __version__ as TRAINITE_VERSION
from trainite.config import (
    OutputConfig,
    ProjectConfig,
)
from trainite.config.registry import (
    REGISTRY,
    ComponentSpec,
    DatasetSpec,
    ModelSpec,
    MODEL_SPECS,
    DATASET_SPECS,
    TRAINER_SPECS,
    PREPROCESSOR_SPECS,
)
from trainite.shared.utils import dump_config


PACKAGE_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = PACKAGE_ROOT.parent

MODEL_CHOICES = tuple(REGISTRY["models"].keys())
DATASET_CHOICES = tuple(REGISTRY["datasets"].keys())
TRAINER_CHOICES = tuple(REGISTRY["trainers"].keys())


ModelType = Literal[MODEL_CHOICES]  # type: ignore
DatasetType = Literal[DATASET_CHOICES]  # type: ignore
TrainerType = Literal[TRAINER_CHOICES]  # type: ignore


def _replace_many(text: str, replacements: Iterable[tuple[str, str]]) -> str:
    for old, new in replacements:
        text = text.replace(old, new)
    if not text.endswith("\n"):
        text += "\n"
    return text


def _render_template(path: Path, replacements: Iterable[tuple[str, str]] = ()) -> str:
    return _replace_many(path.read_text(), replacements)


def _prompt_text(prompt: str, default: str, instruction: str | None = None) -> str:
    result = questionary.text(prompt, default=default, instruction=instruction).ask()
    if result is None:
        raise SystemExit(0)
    return result.strip() or default


def _prompt_choice(prompt: str, choices: Sequence[str], default: str, instruction: str | None = None) -> str:
    result = questionary.select(
        prompt,
        choices=choices,
        default=default,
        instruction=instruction,
    ).ask()
    if result is None:
        raise SystemExit(0)
    return result


def _prompt_multi_choice(
    prompt: str, choices: Sequence[str], default: Sequence[str] | None = None, instruction: str | None = None
) -> list[str]:
    formatted_choices = [questionary.Choice(c, checked=(c in default if default else False)) for c in choices]
    result = questionary.checkbox(
        prompt,
        choices=formatted_choices,
        instruction=instruction,
    ).ask()
    if result is None or len(result) == 0:
        raise SystemExit("At least one model must be selected.")
    return result


def _project_directory(raw_project_dir: str, force: bool) -> Path:
    raw_path = Path(raw_project_dir).expanduser()

    parent = raw_path.parent
    name = raw_path.name

    def _normalize_name(n: str) -> str:
        n = n.strip().lower()
        # Replace any character that is not alnum, dot, underscore or hyphen with a hyphen
        n = re.sub(r"[^a-z0-9._-]+", "-", n)
        # Collapse consecutive hyphens
        n = re.sub(r"-+", "-", n)
        # Strip leading/trailing separators
        n = n.strip("-_.")
        if not n:
            n = "project"
        if n[0].isdigit():
            n = f"proj-{n}"
        return n

    normalized_name = _normalize_name(name)

    project_dir = (parent / normalized_name).resolve()

    if project_dir.exists():
        if not project_dir.is_dir():
            raise SystemExit(f"{project_dir} is not a directory")
        if any(project_dir.iterdir()) and not force:
            raise SystemExit(
                f"{project_dir} is not empty; choose an empty directory or pass --force to overwrite starter files"
            )
    project_dir.mkdir(parents=True, exist_ok=True)
    return project_dir


def _write_file(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists; pass --force to overwrite it")
    if path.parent:
        path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def generate_uv_project(name: str, version: str, dependencies: list[str]) -> str:
    doc = tomlkit.document()

    deps_arr = tomlkit.item(dependencies)
    deps_arr.multiline(True)

    project = tomlkit.table()
    project.add("name", name)
    project.add("version", version)
    project.add("description", f"{name} - generated by Trainite v{TRAINITE_VERSION}")
    project.add("dependencies", deps_arr)
    project.add("requires-python", ">=3.10")
    doc.add("project", project)

    return tomlkit.dumps(doc)


def parse_dependencies(
    file_path: Path,
) -> tuple[dict[str, str], dict[str, str]]:
    with open(file_path, "r") as f:
        data = tomlkit.parse(f.read())

    # 1. Main dependencies
    required_deps = data["dependency-groups"]["generated"]

    # 2. Optional dependencies
    # ponytail: type-annotate empty list
    other_deps: list[str] = []
    optional_deps = data["project"].get("optional-dependencies", {})
    for group_deps in optional_deps.values():
        other_deps.extend(group_deps)

    # 3. Dependency groups (PEP 735)
    dependency_groups = data["dependency-groups"]
    for group, group_deps in dependency_groups.items():
        if group != "generated":
            other_deps.extend(group_deps)

    dep_map = {}
    other_dep_map = {}

    for dep in required_deps:
        req = Requirement(dep)
        dep_map[req.name] = dep

    for dep in other_deps:
        req = Requirement(dep)
        other_dep_map[req.name] = dep
    return dep_map, other_dep_map


def _module_rewrites(sources: dict[str, Path]) -> list[tuple[str, str]]:
    """Map each copied module's package path to its path in the generated project.

    Derived from the generated file layout itself, so import rewrites can never
    drift out of sync with where files actually land.
    """
    pairs = []
    for dest, src in sources.items():
        src_module = ".".join(src.with_suffix("").parts)
        dest_module = ".".join(Path(dest).with_suffix("").parts)
        pairs.append((src_module, dest_module))
    # Longest first, so one module name never clobbers another that it prefixes
    pairs.sort(key=lambda pair: len(pair[0]), reverse=True)
    return pairs


def _recreation_command(config: "Init", project_name: str) -> str:
    cmd_parts = ["trainite", "init", project_name]
    models = config.model if isinstance(config.model, (tuple, list)) else (config.model,)
    cmd_parts.append(f"--model {' '.join(models)}")
    cmd_parts.append(f"--dataset {config.dataset}")
    cmd_parts.append(f"--trainer {config.trainer}")
    if config.output_root != "outputs":
        cmd_parts.append(f"--output-root {config.output_root}")
    if config.run_name:
        cmd_parts.append(f"--run-name {config.run_name}")
    return " ".join(cmd_parts)


def _build_templates(
    model_specs: Sequence[ModelSpec],
    dataset_spec: DatasetSpec,
    trainer_spec: ComponentSpec,
    preprocessor_spec: ComponentSpec | None,
    project_name: str,
    recreation_command: str = "",
) -> tuple[dict[str, str], list[tuple[str, str]]]:
    specs = [*model_specs, dataset_spec, trainer_spec, preprocessor_spec]
    spec_deps = set()
    for spec in specs:
        if spec is not None:
            spec_deps.update(spec.dependencies)
    required_deps, other_deps = parse_dependencies(PROJECT_ROOT / "pyproject.toml")
    final_deps = set(required_deps.values())
    for dep in spec_deps:
        if dep not in required_deps and dep not in other_deps:
            raise ValueError(f"Dependency '{dep}' required by the selected templates is not listed in pyproject.toml")
        val = required_deps[dep] if dep in required_deps else other_deps[dep]
        final_deps.add(val)

    # Generated file -> source file it is copied from
    sources: dict[str, Path] = {}
    for spec in model_specs:
        sources[f"models/{spec.name}.py"] = spec.implementation_path

    sources.update(
        {
            f"datasets/{dataset_spec.name}.py": dataset_spec.implementation_path,
            "datasets/transformed.py": Path("trainite/datasets/transformed.py"),
            "trainer.py": trainer_spec.implementation_path,
            "utils.py": Path("trainite/shared/utils.py"),
            "main.py": Path("trainite/shared/main.py"),
            "config.py": Path("trainite/config/base.py"),
        }
    )
    if preprocessor_spec:
        sources[f"preprocessors/{preprocessor_spec.name}.py"] = preprocessor_spec.implementation_path

    rewrites = _module_rewrites(sources)
    templates = {dest: _render_template(PROJECT_ROOT / src, rewrites) for dest, src in sources.items()}

    def _docs(spec: Any) -> str:
        if spec is not None and spec.readme_template_path:
            return _render_template(PROJECT_ROOT / spec.readme_template_path)
        return ""

    model_names_str = ", ".join(spec.name for spec in model_specs)
    model_docs_str = "\n\n".join(f"#### {spec.name}\n{_docs(spec)}" for spec in model_specs)

    readme_replacements = [
        ("{{project_name}}", project_name),
        ("{{trainite_version}}", TRAINITE_VERSION),
        ("{{recreation_command}}", recreation_command),
        ("{{model_name}}", model_names_str),
        ("{{model_docs}}", model_docs_str),
        ("{{dataset_name}}", dataset_spec.name),
        ("{{dataset_docs}}", _docs(dataset_spec)),
        ("{{trainer_name}}", trainer_spec.name),
        ("{{trainer_docs}}", _docs(trainer_spec)),
        ("{{preprocessor_name}}", preprocessor_spec.name if preprocessor_spec else "None"),
        ("{{preprocessor_docs}}", _docs(preprocessor_spec)),
    ]
    templates["README.md"] = _render_template(
        PROJECT_ROOT / "trainite/templates/project/README.md", readme_replacements
    )
    templates["pyproject.toml"] = generate_uv_project(
        name=project_name, version="0.1.0", dependencies=sorted(final_deps)
    )

    return templates, rewrites


def run_interactive_mode() -> None:
    project_dir = _prompt_text(
        "Project directory:",
        "my-cool-experiment",
        "Directory to create the starter project in \n",
    )
    models = _prompt_multi_choice(
        "Model(s):",
        MODEL_CHOICES,
        default=["rope-transformer"],
        instruction="Select starter model template(s) to include (use space to select)",
    )
    if len(models) > 1:
        primary_model = _prompt_choice(
            "Primary active model in config.yaml:",
            models,
            default=models[0],
            instruction="Choose which model is configured as default active in config.yaml",
        )
        models = [primary_model] + [m for m in models if m != primary_model]
    dataset = _prompt_choice(
        "Dataset:",
        DATASET_CHOICES,
        DATASET_CHOICES[0],
        "Starter dataset template to use",
    )
    trainer = _prompt_choice(
        "Trainer:",
        TRAINER_CHOICES,
        TRAINER_CHOICES[0],
        "Starter trainer template to use",
    )
    output_root = _prompt_text("Output directory:", "outputs", "Output directory for generated files \n")
    run_name = _prompt_text(
        "Run name:",
        f"{models[0]}__{dataset}",
        "Run name for generated config (used in output paths and logging) \n",
    )

    config = Init(
        project_dir=project_dir,
        model=tuple(models),
        dataset=dataset,
        trainer=trainer,
        output_root=output_root,
        run_name=run_name,
        force=False,
    )

    init_project(config)


def _update_targets(config: Any, rewrites: Sequence[tuple[str, str]]) -> None:
    """Rewrite ``_target_`` and ``collate_fn_target`` import paths to point at the generated project's modules."""
    if isinstance(config, BaseModel):
        for attr in ("target", "collate_fn_target"):
            val = getattr(config, attr, None)
            if isinstance(val, str):
                for old_module, new_module in rewrites:
                    if val.startswith(old_module + "."):
                        setattr(config, attr, new_module + val[len(old_module) :])
                        break
        for field in config.model_fields:
            if (val := getattr(config, field)) is not None:
                _update_targets(val, rewrites)


class Init(BaseModel):
    """Generate a starter training project.

    Run ``trainite init`` without any arguments to enter interactive mode,
    where each option is prompted one at a time.

    Args:
        project_dir: Directory to create the starter project in.
        model: Starter model template(s) to use.
        dataset: Starter dataset template to use.
        trainer: Starter trainer template to use.
        output_root: Output root for generated config.
        run_name: Run name for generated config.
        force: Overwrite existing starter files.
    """

    project_dir: tyro.conf.Positional[str] = "my-cool-experiment"
    model: tuple[ModelType, ...] = ("rope-transformer",)
    dataset: DatasetType = "string-reverse"
    trainer: TrainerType = "decoder-trainer"
    output_root: str = "outputs"
    run_name: str = ""
    force: bool = False

    @field_validator("model", mode="before")
    @classmethod
    def validate_models(cls, v: Any) -> tuple[str, ...]:
        if isinstance(v, str):
            v = (v,)
        if isinstance(v, (list, tuple)):
            if not v:
                raise ValueError("At least one model must be specified.")
            if len(v) != len(set(v)):
                raise ValueError("Duplicate model entries are not allowed.")
            return tuple(v)
        return v


def init_project(config: Init) -> None:
    """Generate a starter training project.

    Args:
        config: Configuration for the starter project.
    """

    project_dir = config.project_dir
    models = config.model
    dataset = config.dataset
    trainer = config.trainer
    output_root = config.output_root
    run_name = config.run_name
    force = config.force

    primary_model = models[0]
    resolved_run_name = run_name or f"{primary_model}__{dataset}"
    resolved_project_dir = _project_directory(project_dir, force)

    output_config = OutputConfig(root=output_root, run_name=resolved_run_name)

    model_specs = [MODEL_SPECS[m] for m in models]
    primary_model_spec = model_specs[0]
    dataset_spec = DATASET_SPECS[dataset]
    trainer_spec = TRAINER_SPECS[trainer]
    preprocessor_spec = (
        PREPROCESSOR_SPECS[dataset_spec.preprocessor_spec_name] if dataset_spec.preprocessor_spec_name else None
    )

    recreation_cmd = _recreation_command(config, resolved_project_dir.name)

    # Build templates for the starter project
    templates, rewrites = _build_templates(
        model_specs, dataset_spec, trainer_spec, preprocessor_spec, resolved_project_dir.name, recreation_cmd
    )

    # Instantiate configs from specs (primary model is used for default config.yaml)
    model_component = primary_model_spec.config_cls(collate_fn_target=primary_model_spec.collate_fn_target)
    data_config = dataset_spec.config_cls()
    trainer_component = trainer_spec.config_cls()

    preprocessor_component = preprocessor_spec.config_cls() if preprocessor_spec else None

    starter_config = ProjectConfig(
        preprocessor=preprocessor_component,
        model=model_component,
        data=data_config,
        trainer=trainer_component,
        output=output_config,
    )

    # Update targets to point to the local project structure
    _update_targets(starter_config, rewrites)

    dump_config(starter_config, resolved_project_dir / "config.yaml")
    for filename, content in templates.items():
        _write_file(resolved_project_dir / filename, content, force)

    print("\n Generated config.yaml")
    for filename in templates:
        print(f" Generated {filename}")
