import argparse
import inspect
import re
import textwrap
from pathlib import Path
from typing import Iterable, Sequence

import tomlkit
from packaging.requirements import Requirement

from trainite.config import (
    ComponentConfig,
    DataConfig,
    DataLoaderConfig,
    OutputConfig,
    ProjectConfig,
    SplitConfig,
    dump_config,
)
from trainite.config.registry import (
    REGISTRY,
    get_dataset_spec,
    get_model_spec,
    get_trainer_spec,
)

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = PACKAGE_ROOT.parent

MODEL_CHOICES = tuple(REGISTRY["models"].keys())
DATASET_CHOICES = tuple(REGISTRY["datasets"].keys())
TRAINER_CHOICES = tuple(REGISTRY["trainers"].keys())


def _replace_many(text: str, replacements: Iterable[tuple[str, str]]) -> str:
    for old, new in replacements:
        text = text.replace(old, new)
    if not text.endswith("\n"):
        text += "\n"
    return text


def _render_template(path: Path, replacements: Iterable[tuple[str, str]] = ()) -> str:
    return _replace_many(path.read_text(), replacements)


def _render_class_source(cls: type) -> str:
    return textwrap.dedent(inspect.getsource(cls)).strip()


def _prompt_text(prompt: str, default: str) -> str:
    value = input(f"{prompt} [{default}]: ").strip()
    return value or default


def _prompt_choice(prompt: str, choices: Sequence[str], default: str) -> str:
    selected = _prompt_text(f"{prompt} ({' / '.join(choices)})", default)
    if selected not in choices:
        raise SystemExit(f"Unsupported choice: {selected}")
    return selected


def _project_directory(raw_project_dir: str, force: bool) -> Path:
    raw_path = Path(raw_project_dir).expanduser()

    parent = raw_path.parent
    name = raw_path.name

    def _normalize_name(n: str) -> str:
        n = n.strip().lower()
        # Replace any character that is not alnum, dot, underscore or hyphen with a hyphen
        n = re.sub(r"[^a-z0-9._-]+", "-", n)
        # Collapse consecutive hyphens
        n = re.sub(r"-+", "-", n)
        # Strip leading/trailing separators
        n = n.strip("-_.")
        if not n:
            n = "project"
        if n[0].isdigit():
            n = f"proj-{n}"
        return n

    normalized_name = _normalize_name(name)

    project_dir = (parent / normalized_name).resolve()

    if project_dir.exists():
        if not project_dir.is_dir():
            raise SystemExit(f"{project_dir} is not a directory")
        if any(project_dir.iterdir()) and not force:
            raise SystemExit(
                f"{project_dir} is not empty; choose an empty directory or pass --force to overwrite starter files"
            )
    project_dir.mkdir(parents=True, exist_ok=True)
    return project_dir


def _write_file(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists; pass --force to overwrite it")
    if path.parent:
        path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def generate_uv_project(name: str, version: str, dependencies: list[str]) -> str:
    doc = tomlkit.document()

    deps_arr = tomlkit.item(dependencies)
    deps_arr.multiline(True)

    project = tomlkit.table()
    project.add("name", name)
    project.add("version", version)
    project.add("description", f"{name} - generated by Trainite")
    project.add("dependencies", deps_arr)
    project.add("requires-python", ">=3.10")
    doc.add("project", project)

    return tomlkit.dumps(doc)


def parse_dependencies(
    file_path: Path,
) -> tuple[dict[str, str], dict[str, str]]:
    with open(file_path, "r") as f:
        data = tomlkit.parse(f.read())

    # 1. Main dependencies
    required_deps = data["dependency-groups"]["generated"]

    # 2. Optional dependencies
    other_deps = []
    optional_deps = data["project"].get("optional-dependencies", {})
    for group_deps in optional_deps.values():
        other_deps.extend(group_deps)

    # 3. Dependency groups (PEP 735)
    dependency_groups = data["dependency-groups"]
    for group, group_deps in dependency_groups.items():
        if group != "generated":
            other_deps.extend(group_deps)

    dep_map = {}
    other_dep_map = {}

    for dep in required_deps:
        req = Requirement(dep)
        dep_map[req.name] = dep

    for dep in other_deps:
        req = Requirement(dep)
        other_dep_map[req.name] = dep
    return dep_map, other_dep_map


def _build_templates(
    model_name: str, dataset_name: str, trainer_name: str, project_name: str
) -> dict[str, str]:
    model_spec = get_model_spec(model_name)
    dataset_spec = get_dataset_spec(dataset_name)
    trainer_spec = get_trainer_spec(trainer_name)
    spec_deps = set()
    for spec in [model_spec, dataset_spec, trainer_spec]:
        spec_deps.update(spec.dependencies)
    required_deps, other_deps = parse_dependencies(PROJECT_ROOT / "pyproject.toml")
    final_deps = set(required_deps.values())
    for dep in spec_deps:
        if dep not in required_deps and dep not in other_deps:
            raise ValueError(
                f"Dependency '{dep}' required by the selected templates is not listed in pyproject.toml"
            )
        val = required_deps[dep] if dep in required_deps else other_deps[dep]
        final_deps.add(val)
    model_docs = ""
    if model_spec.readme_template_path:
        model_docs = _render_template(PROJECT_ROOT / model_spec.readme_template_path)

    dataset_docs = ""
    if dataset_spec.readme_template_path:
        dataset_docs = _render_template(
            PROJECT_ROOT / dataset_spec.readme_template_path
        )

    trainer_docs = ""
    if trainer_spec.readme_template_path:
        trainer_docs = _render_template(
            PROJECT_ROOT / trainer_spec.readme_template_path
        )

    return {
        f"models/{model_spec.name}.py": _render_template(
            PROJECT_ROOT / model_spec.implementation_path,
            model_spec.template_replacements,
        ),
        f"dataset/{dataset_spec.name}.py": _render_template(
            PROJECT_ROOT / dataset_spec.implementation_path,
            dataset_spec.template_replacements,
        ),
        "trainer.py": _render_template(
            PROJECT_ROOT / trainer_spec.implementation_path,
            trainer_spec.template_replacements,
        ),
        "utils.py": _render_template(
            PROJECT_ROOT / "trainite/utils.py",
            [("trainite.config", "config")],
        ),
        "config.py": _render_template(PROJECT_ROOT / "trainite/config/base.py", []),
        "main.py": _render_template(
            PROJECT_ROOT / "trainite/main.py",
            [
                (
                    "trainite.config",
                    "config",
                ),
                (
                    "from trainite.trainers import PreTrainer",
                    f"from trainer import {trainer_spec.implementation_symbol}",
                ),
                (
                    "trainer = PreTrainer(config)",
                    f"trainer = {trainer_spec.implementation_symbol}(config)",
                ),
            ],
        ),
        "README.md": _render_template(
            PROJECT_ROOT / "trainite/templates/project/README.md",
            [
                ("{{project_name}}", project_name),
                ("{{model_name}}", model_spec.name),
                ("{{model_docs}}", model_docs),
                ("{{dataset_name}}", dataset_spec.name),
                ("{{dataset_docs}}", dataset_docs),
                ("{{trainer_name}}", trainer_spec.name),
                ("{{trainer_docs}}", trainer_docs),
            ],
        ),
        "pyproject.toml": generate_uv_project(
            name=project_name,
            version="0.1.0",
            dependencies=sorted(final_deps),
        ),
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog="trainite")
    subparsers = parser.add_subparsers(dest="command", required=True)

    init_parser = subparsers.add_parser(
        "init", help="Generate a starter training project"
    )
    init_parser.add_argument(
        "project_dir", nargs="?", help="Directory to create the starter project in"
    )
    init_parser.add_argument(
        "--model", choices=MODEL_CHOICES, help="Starter model template to use"
    )
    init_parser.add_argument(
        "--dataset", choices=DATASET_CHOICES, help="Starter dataset template to use"
    )
    init_parser.add_argument("--output-root", help="Output root for generated config")
    init_parser.add_argument("--run-name", help="Run name for generated config")
    init_parser.add_argument(
        "--trainer", choices=TRAINER_CHOICES, help="Starter trainer template to use"
    )
    init_parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing starter files",
    )
    init_parser.add_argument(
        "--yes",
        "-y",
        action="store_true",
        help="Use defaults for anything not provided and skip prompts",
    )
    init_parser.set_defaults(func=init_project)

    return parser


def init_project(args: argparse.Namespace) -> None:
    if args.yes:
        project_dir = args.project_dir or "my-cool-experiment"
        model_name = args.model or MODEL_CHOICES[0]
        dataset_name = args.dataset or DATASET_CHOICES[0]
        trainer_name = args.trainer or TRAINER_CHOICES[0]
        output_root = args.output_root or "outputs"
        run_name = args.run_name or f"{model_name}__{dataset_name}"
    else:
        project_dir = args.project_dir or _prompt_text(
            "Project directory", "my-cool-experiment"
        )
        model_name = args.model or _prompt_choice(
            "Model", MODEL_CHOICES, MODEL_CHOICES[0]
        )
        dataset_name = args.dataset or _prompt_choice(
            "Dataset", DATASET_CHOICES, DATASET_CHOICES[0]
        )
        trainer_name = args.trainer or _prompt_choice(
            "Trainer", TRAINER_CHOICES, TRAINER_CHOICES[0]
        )
        output_root = args.output_root or _prompt_text("Output directory", "outputs")
        run_name = args.run_name or _prompt_text(
            "Run name", f"{model_name}__{dataset_name}"
        )

    project_dir = _project_directory(project_dir, args.force)

    output_config = OutputConfig(root=output_root, run_name=run_name)

    # Build templates for the starter project
    templates = _build_templates(
        model_name, dataset_name, trainer_name, project_dir.name
    )

    model_spec = get_model_spec(model_name)
    dataset_spec = get_dataset_spec(dataset_name)
    trainer_spec = get_trainer_spec(trainer_name)

    # Update config to point to the correct builder functions for the model and dataset
    model_component = model_spec.config_cls()
    trainer_component = trainer_spec.config_cls()

    model_component.target = f"models.{model_spec.name}.{model_spec.builder_symbol}"

    # Build train split
    train_dataset = dataset_spec.config_cls()
    train_dataset.target = f"dataset.{dataset_spec.name}.{dataset_spec.builder_symbol}"

    # Build val split
    val_dataset = dataset_spec.config_cls()
    val_dataset.target = f"dataset.{dataset_spec.name}.{dataset_spec.builder_symbol}"

    collate_fn_config = None
    if dataset_spec.collate_fn_symbol:
        collate_fn_config = ComponentConfig(
            _target_=f"dataset.{dataset_spec.name}.{dataset_spec.collate_fn_symbol}"
        )

    starter_config = ProjectConfig(
        model=model_component,
        data=DataConfig(
            train=SplitConfig(
                dataset=train_dataset,
                dataloader=DataLoaderConfig(
                    batch_size=32,
                    shuffle=True,
                    collate_fn=collate_fn_config,
                ),
            ),
        ),
        trainer=trainer_component,
        output=output_config,
    )

    dump_config(starter_config, project_dir / "config.yaml")
    for filename, content in templates.items():
        _write_file(project_dir / filename, content, args.force)

    print(f"Generated starter project in {project_dir}")
    for filename in ["config.yaml", *templates]:
        print(f"- {filename}")


def main(argv: Sequence[str] | None = None) -> None:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)
