"""Trainite starter project generator.

This module implements the two-track model for project generation:
1. Copied files: Source files from trainite are copied verbatim and run through
   import path rewriting to make them local to the generated project structure.
2. Synthesized files: Files like config.py, pyproject.toml, and README.md are
   generated dynamically based on selected components.
"""

import re
from pathlib import Path
from typing import Any, Iterable, Literal, NamedTuple, Sequence

import questionary
import tomlkit
import tyro
from packaging.requirements import Requirement
from pydantic import BaseModel

from trainite.config import OutputConfig, ProjectConfigBase
from trainite.config.registry import (
    REGISTRY,
    get_dataset_spec,
    get_model_spec,
    get_preprocessor_spec,
    get_trainer_spec,
    DatasetSpec,
    ModelSpec,
    PreProcessorSpec,
    TrainerSpec,
)
from trainite.shared.utils import dump_config

PACKAGE_ROOT = Path(__file__).resolve().parents[1]
PROJECT_ROOT = PACKAGE_ROOT.parent

MODEL_CHOICES = tuple(REGISTRY["models"].keys())
DATASET_CHOICES = tuple(REGISTRY["datasets"].keys())
TRAINER_CHOICES = tuple(REGISTRY["trainers"].keys())

ModelType = Literal[MODEL_CHOICES]  # type: ignore
DatasetType = Literal[DATASET_CHOICES]  # type: ignore
TrainerType = Literal[TRAINER_CHOICES]  # type: ignore


class Specs(NamedTuple):
    model: ModelSpec
    dataset: DatasetSpec
    trainer: TrainerSpec
    preprocessor: PreProcessorSpec | None


# --- Interactive prompts ---


def _prompt_text(prompt: str, default: str, instruction: str | None = None) -> str:
    result = questionary.text(prompt, default=default, instruction=instruction).ask()
    if result is None:
        raise SystemExit(0)
    return result.strip() or default


def _prompt_choice(prompt: str, choices: Sequence[str], default: str, instruction: str | None = None) -> str:
    result = questionary.select(
        prompt,
        choices=choices,
        default=default,
        instruction=instruction,
    ).ask()
    if result is None:
        raise SystemExit(0)
    return result


# --- Filesystem helpers ---


def _project_directory(raw_project_dir: str, force: bool) -> Path:
    raw_path = Path(raw_project_dir).expanduser()
    parent = raw_path.parent
    name = raw_path.name

    def _normalize_name(n: str) -> str:
        n = n.strip().lower()
        n = re.sub(r"[^a-z0-9._-]+", "-", n)
        n = re.sub(r"-+", "-", n)
        n = n.strip("-_.")
        if not n:
            n = "project"
        if n[0].isdigit():
            n = f"proj-{n}"
        return n

    normalized_name = _normalize_name(name)
    project_dir = (parent / normalized_name).resolve()

    if project_dir.exists():
        if not project_dir.is_dir():
            raise SystemExit(f"{project_dir} is not a directory")
        if any(project_dir.iterdir()) and not force:
            raise SystemExit(
                f"{project_dir} is not empty; choose an empty directory or pass --force to overwrite starter files"
            )
    project_dir.mkdir(parents=True, exist_ok=True)
    return project_dir


def _write_file(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise FileExistsError(f"{path} already exists; pass --force to overwrite it")
    if path.parent:
        path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


# --- Import-path rewriting ---


def _module_rewrites(sources: dict[str, Path]) -> list[tuple[str, str]]:
    rewrites = [("trainite.config", "config")]
    for gen_path_str, src_path in sources.items():
        src_posix = src_path.with_suffix("").as_posix()
        src_module = src_posix.replace("/", ".")
        gen_module = gen_path_str.removesuffix(".py").replace("/", ".")
        rewrites.append((src_module, gen_module))
    rewrites.sort(key=lambda x: len(x[0]), reverse=True)
    return rewrites


def _rewrite_modules(text: str, rewrites: Iterable[tuple[str, str]]) -> str:
    for old, new in rewrites:
        text = re.sub(rf"\b{re.escape(old)}\b", new, text)
    if not text.endswith("\n"):
        text += "\n"
    return text


def _rewrite_name(dotted: str, rewrites: Sequence[tuple[str, str]]) -> str:
    for old, new in rewrites:
        if dotted == old or dotted.startswith(old + "."):
            return new + dotted[len(old) :]
    return dotted


# --- pyproject.toml / dependencies ---


def generate_uv_project(name: str, version: str, dependencies: list[str]) -> str:
    doc = tomlkit.document()
    deps_arr = tomlkit.item(dependencies)
    deps_arr.multiline(True)

    project = tomlkit.table()
    project.add("name", name)
    project.add("version", version)
    project.add("description", f"{name} - generated by Trainite")
    project.add("dependencies", deps_arr)
    project.add("requires-python", ">=3.10")
    doc.add("project", project)

    return tomlkit.dumps(doc)


def parse_dependencies(file_path: Path) -> tuple[dict[str, str], dict[str, str]]:
    with open(file_path, "r") as f:
        data = tomlkit.parse(f.read())

    required_deps = data["dependency-groups"]["generated"]

    other_deps: list[str] = []
    optional_deps = data["project"].get("optional-dependencies", {})
    for group_deps in optional_deps.values():
        other_deps.extend(group_deps)

    dependency_groups = data["dependency-groups"]
    for group, group_deps in dependency_groups.items():
        if group != "generated":
            other_deps.extend(group_deps)

    dep_map = {}
    other_dep_map = {}

    for dep in required_deps:
        req = Requirement(dep)
        dep_map[req.name] = dep

    for dep in other_deps:
        req = Requirement(dep)
        other_dep_map[req.name] = dep
    return dep_map, other_dep_map


def _collect_dependencies(specs: Specs) -> list[str]:
    spec_deps = set()
    for spec in [specs.model, specs.dataset, specs.trainer, specs.preprocessor]:
        if spec is not None:
            spec_deps.update(spec.dependencies)
    required_deps, other_deps = parse_dependencies(PROJECT_ROOT / "pyproject.toml")
    final_deps = set(required_deps.values())
    for dep in spec_deps:
        if dep not in required_deps and dep not in other_deps:
            raise ValueError(f"Dependency '{dep}' required by the selected templates is not listed in pyproject.toml")
        val = required_deps[dep] if dep in required_deps else other_deps[dep]
        final_deps.add(val)
    return sorted(list(final_deps))


# --- config.py aggregator ---


def _render_config_py(
    model_cfg: type,
    data_cfg: type,
    trainer_cfg: type,
    preprocessor_cfg: type | None,
    rewrites: Sequence[tuple[str, str]],
) -> str:
    template_path = PROJECT_ROOT / "trainite/templates/project/config.py"
    content = template_path.read_text()

    import_base = _rewrite_name("trainite.config.base", rewrites)
    model_module = _rewrite_name(model_cfg.__module__, rewrites)
    data_module = _rewrite_name(data_cfg.__module__, rewrites)
    trainer_module = _rewrite_name(trainer_cfg.__module__, rewrites)

    imports_list = [
        f"from {model_module} import {model_cfg.__name__} as ModelConfig",
        f"from {data_module} import {data_cfg.__name__} as DataConfig",
        f"from {trainer_module} import {trainer_cfg.__name__} as TrainerConfig",
    ]

    if preprocessor_cfg is not None:
        prep_module = _rewrite_name(preprocessor_cfg.__module__, rewrites)
        imports_list.append(f"from {prep_module} import {preprocessor_cfg.__name__} as PreprocessorConfig")
        preprocessor_def = ""
    else:
        preprocessor_def = "PreprocessorConfig = None"

    imports_str = "\n".join(imports_list)
    if preprocessor_def:
        imports_str = f"{imports_str}\n{preprocessor_def}"

    import re

    # Strip linter helper block
    content = re.sub(
        r"# --- template-checking-only ---.*?# --- end-template-checking-only ---\n*",
        "",
        content,
        flags=re.DOTALL,
    )

    actual_imports = f"from {import_base} import ProjectConfigBase\n{imports_str}"

    content = content.replace("# {{imports}}", actual_imports)
    return content


# --- Template (file-content) building ---


def _render_readme(specs: Specs, project_name: str) -> str:
    model_docs = ""
    if specs.model.readme_template_path:
        model_docs = (PROJECT_ROOT / specs.model.readme_template_path).read_text()

    dataset_docs = ""
    if specs.dataset.readme_template_path:
        dataset_docs = (PROJECT_ROOT / specs.dataset.readme_template_path).read_text()

    trainer_docs = ""
    if specs.trainer.readme_template_path:
        trainer_docs = (PROJECT_ROOT / specs.trainer.readme_template_path).read_text()

    preprocessor_name = specs.preprocessor.name if specs.preprocessor else "None"
    preprocessor_docs = ""
    if specs.preprocessor and specs.preprocessor.readme_template_path:
        preprocessor_docs = (PROJECT_ROOT / specs.preprocessor.readme_template_path).read_text()

    readme_path = PROJECT_ROOT / "trainite/templates/project/README.md"
    content = readme_path.read_text()

    replacements = [
        ("{{project_name}}", project_name),
        ("{{model_name}}", specs.model.name),
        ("{{model_docs}}", model_docs),
        ("{{dataset_name}}", specs.dataset.name),
        ("{{dataset_docs}}", dataset_docs),
        ("{{trainer_name}}", specs.trainer.name),
        ("{{trainer_docs}}", trainer_docs),
        ("{{preprocessor_name}}", preprocessor_name),
        ("{{preprocessor_docs}}", preprocessor_docs),
    ]

    for placeholder, val in replacements:
        content = content.replace(placeholder, val)
    return content


def _source_map(specs: Specs) -> dict[str, Path]:
    """Builds a map of generated files to their trainite source files.

    Note on config_base.py vs config.py:
    StringReverseDataConfig (in datasets/string_reverse.py) inherits DataWithAutoSplit,
    a real structural base class (split ratios + validator, not a marker).
    If that base class lived inside config.py, and config.py also imports
    StringReverseDataConfig to build the concrete ProjectConfig, we get a circular
    import cycle (config.py -> datasets/string_reverse.py -> config.py).
    By separating structural base classes into config_base.py (a leaf module with
    no external components imports) and config.py (the root module that imports both
    config_base.py and component configs), we avoid circular import cycles entirely.
    """
    mapping = {
        f"models/{specs.model.name}.py": specs.model.implementation_path,
        f"datasets/{specs.dataset.name}.py": specs.dataset.implementation_path,
        "datasets/transformed.py": Path("trainite/datasets/transformed.py"),
        "trainer.py": specs.trainer.implementation_path,
        "utils.py": Path("trainite/shared/utils.py"),
        "main.py": Path("trainite/shared/main.py"),
        "config_base.py": Path("trainite/config/base.py"),
    }
    if specs.preprocessor:
        mapping[f"preprocessors/{specs.preprocessor.name}.py"] = specs.preprocessor.implementation_path
    return mapping


def _build_templates(
    specs: Specs, sources: dict[str, Path], rewrites: list[tuple[str, str]], project_name: str
) -> dict[str, str]:
    templates = {}

    def _checked(dest: str, content: str) -> str:
        if leftover := re.search(r"\btrainite\.\w", content):
            raise ValueError(
                f"{dest}: '{leftover.group()}' was not rewritten; add its source to the generated file map"
            )
        return content

    for dest, src in sources.items():
        content = src.read_text()
        rewritten = _rewrite_modules(content, rewrites)
        templates[dest] = _checked(dest, rewritten)

    config_py_content = _render_config_py(
        specs.model.config_cls,
        specs.dataset.config_cls,
        specs.trainer.config_cls,
        specs.preprocessor.config_cls if specs.preprocessor else None,
        rewrites,
    )
    templates["config.py"] = _checked("config.py", config_py_content)
    templates["README.md"] = _render_readme(specs, project_name)
    dependencies = _collect_dependencies(specs)
    templates["pyproject.toml"] = generate_uv_project(project_name, "0.1.0", dependencies)

    return templates


# --- Starter config object (dumped to config.yaml) ---


def _inject_collate_fn(model_spec: ModelSpec, data_config: Any) -> None:
    if not model_spec.collate_fn_target:
        return

    from trainite.config.base import TargetedConfig

    if model_spec.collate_fn_config_cls:
        collate_fn_instance = model_spec.collate_fn_config_cls()
        collate_fn_val = TargetedConfig.model_validate(collate_fn_instance.model_dump(by_alias=True))
    else:
        collate_fn_val = TargetedConfig(_target_=model_spec.collate_fn_target)

    def _inject(config: Any) -> None:
        dataloader = getattr(config, "dataloader", None)
        if dataloader is not None:
            dataloader.collate_fn = collate_fn_val
        for split in ["train", "val", "test"]:
            split_config = getattr(config, split, None)
            if split_config is not None:
                _inject(split_config)

    _inject(data_config)


def _update_targets(config: Any, rewrites: Sequence[tuple[str, str]]) -> None:
    if isinstance(config, BaseModel) and hasattr(config, "target"):
        target = getattr(config, "target")
        if isinstance(target, str):
            setattr(config, "target", _rewrite_name(target, rewrites))
    if isinstance(config, BaseModel):
        for field in type(config).model_fields:
            if (val := getattr(config, field)) is not None:
                _update_targets(val, rewrites)


def _build_starter_config(
    specs: Specs, output_config: OutputConfig, rewrites: Sequence[tuple[str, str]]
) -> ProjectConfigBase:
    model_component = specs.model.config_cls()
    data_config = specs.dataset.config_cls()
    trainer_component = specs.trainer.config_cls()
    preprocessor_component = specs.preprocessor.config_cls() if specs.preprocessor else None

    _inject_collate_fn(specs.model, data_config)

    starter_config = ProjectConfigBase(
        preprocessor=preprocessor_component,
        model=model_component,
        data=data_config,
        trainer=trainer_component,
        output=output_config,
    )

    _update_targets(starter_config, rewrites)
    return starter_config


# --- Entry points ---


class Init(BaseModel):
    """Generate a starter training project.

    Run ``trainite init`` without any arguments to enter interactive mode,
    where each option is prompted one at a time.

    Args:
        project_dir: Directory to create the starter project in.
        model: Starter model template to use.
        dataset: Starter dataset template to use.
        trainer: Starter trainer template to use.
        output_root: Output root for generated config.
        run_name: Run name for generated config.
        force: Overwrite existing starter files.
    """

    project_dir: tyro.conf.Positional[str] = "my-cool-experiment"
    model: ModelType = "transformer"
    dataset: DatasetType = "string-reverse"
    trainer: TrainerType = "decoder-trainer"
    output_root: str = "outputs"
    run_name: str = ""
    force: bool = False


def _resolve_specs(config: Init) -> Specs:
    model_spec = get_model_spec(config.model)
    dataset_spec = get_dataset_spec(config.dataset)
    trainer_spec = get_trainer_spec(config.trainer)
    preprocessor_spec = (
        get_preprocessor_spec(dataset_spec.preprocessor_spec_name) if dataset_spec.preprocessor_spec_name else None
    )
    return Specs(
        model=model_spec,
        dataset=dataset_spec,
        trainer=trainer_spec,
        preprocessor=preprocessor_spec,
    )


def init_project(config: Init) -> None:
    project_dir = _project_directory(config.project_dir, config.force)
    specs = _resolve_specs(config)
    sources = _source_map(specs)
    rewrites = _module_rewrites(sources)

    templates = _build_templates(specs, sources, rewrites, project_dir.name)

    resolved_run_name = config.run_name or f"{config.model}__{config.dataset}"
    output_config = OutputConfig(root=config.output_root, run_name=resolved_run_name)
    starter_config = _build_starter_config(specs, output_config, rewrites)

    dump_config(starter_config, project_dir / "config.yaml")
    for filename, content in templates.items():
        _write_file(project_dir / filename, content, config.force)

    print("\n✔ Generated config.yaml")
    for filename in templates:
        print(f"✔ Generated {filename}")


def run_interactive_mode() -> None:
    project_dir = _prompt_text(
        "Project directory:",
        "my-cool-experiment",
        "Directory to create the starter project in \n",
    )
    model = _prompt_choice("Model:", MODEL_CHOICES, MODEL_CHOICES[0], "Starter model template to use")
    dataset = _prompt_choice(
        "Dataset:",
        DATASET_CHOICES,
        DATASET_CHOICES[0],
        "Starter dataset template to use",
    )
    trainer = _prompt_choice(
        "Trainer:",
        TRAINER_CHOICES,
        TRAINER_CHOICES[0],
        "Starter trainer template to use",
    )
    output_root = _prompt_text("Output directory:", "outputs", "Output directory for generated files \n")
    run_name = _prompt_text(
        "Run name:",
        f"{model}__{dataset}",
        "Run name for generated config (used in output paths and logging) \n",
    )

    config = Init(
        project_dir=project_dir,
        model=model,
        dataset=dataset,
        trainer=trainer,
        output_root=output_root,
        run_name=run_name,
        force=False,
    )

    init_project(config)
