name: code style check and type check

on:
  push:
    branches: [main, "develop"]
  pull_request:
    branches: [main, "develop"]
  workflow_dispatch:

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install uv and dependencies
        uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          enable-cache: true
          python-version: 3.11

      - name: Sync dev dependencies and run pre-commit hooks
        run: |
          uv sync --locked --all-extras --dev
          uv run pre-commit run --all-files
