name: code style check

on:
  push:
    branches: [main, "develop"]
  pull_request:
    branches: [main, "develop"]
  workflow_dispatch:

jobs:
  code-style-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: checks code style
        uses: pre-commit/action@v3.0.1
